document.write('<div class = "toc">');
document.write('	<ul>');
document.write('		<center>');
document.write('			<li>');
document.write('			<b>Contents</b>');
document.write('			</li>');
document.write('			</center>');
document.write('');
document.write('');
document.write('		<button data-for = "instant1" type="button" class="collapsibleidx" id="here_instant" onclick="carryOn(\'instant1\');">');
document.write('			1 <a href="#" onclick="return false;">Perturbations</a>');
document.write('		</button>');
document.write('');
document.write('		<div class = "content coll" id = "instant1">');
document.write('			<div class = "toc2">');
document.write('				<li>1.1 <a href="augur.html" onclick="store(1);setSwitch();"><button class="btn">Augur</button></a></li>');
document.write('				<li>1.2 <a href="rng.html" onclick="store(2);setSwitch();"><button class="btn">43% Random</button></a></li>');
document.write('				<li>1.3 <a href="blinker.html" onclick="store(3);setSwitch();"><button class="btn">Blink!</button></a></li>');
document.write('				<li>1.4 <a href="stop.html" onclick="store(4);setSwitch();"><button class="btn">I Can\'t Stop</button></a></li>');
document.write('			</div>');
document.write('		</div>');
document.write('');
document.write('		<button data-for = "instant2" type="button" class="collapsibleidx" id="here_instant" onclick="carryOn(\'instant2\');">');
document.write('			2 <a href="#" onClick="return false;">Undersampled</a>');
document.write('		</button>');
document.write('');
document.write('		<div class = "content coll" id = "instant2">');
document.write('			<div class = "toc2">');
document.write('				<li>2.1 <a href="220grit.html" onclick="store(5);setSwitch();"><button class="btn">220 Grit</button></a></li>');
document.write('				<li>2.2 <a href="irrational.html" onclick="store(6);setSwitch();"><button class="btn">Irrational</button></a></li>');
document.write('				<li>2.3 <a href="sunset.html" onclick="store(7);setSwitch();"><button class="btn">Sunset</button></a></li>');
document.write('				<li>2.4 <a href="holder1.html" onclick="store(8);setSwitch();"><button class="btn">Coprime</button></a></li>');
document.write('				<li>2.5 <a href="holder2.html" onclick="store(9);setSwitch();"><button class="btn">Standard</button></a></li>');
document.write('				<li>2.6 <a href="traces.html" onclick="store(10);setSwitch();"><button class="btn">Test Relic</button></a></li>');
document.write('				<li>--- <a href="thoughts.html" onclick="store(11);setSwitch();"><button class="btn">Thoughts</button></a></li>');
document.write('			</div>');
document.write('		</div>');
document.write('');
document.write('		<button data-for = "instant3" type="button" class="collapsibleidx" id="here_instant" onclick="carryOn(\'instant3\');">');
document.write('			3 <a href="#" onClick="return false;">Digital Purgatory</a>');
document.write('		</button>');
document.write('');
document.write('		<div class = "content coll" id = "instant3">');
document.write('			<div class = "toc2">');
document.write('				<li>3.1 <a href="spodophyllum.html" onclick="store(12);setSwitch();"><button class="btn">S. Podophyllum</button></a></li>');
document.write('				<li>3.2 <a href="untitled.html" onclick="store(13);setSwitch();"><button class="btn">Untitled</button></a></li>');
document.write('				<li>3.3 <a href="finding_myself.html" onclick="store(14);setSwitch();"><button class="btn">Finding Myself</button></a></li>');
document.write('			</div>');
document.write('		</div>');
document.write('');
document.write('		<button data-for = "instant4" type="button" class="collapsibleidx" id="here_instant" onclick="carryOn(\'instant4\');">');
document.write('			4 <a href="#" onClick="return false;">Perpetuum Mobile</a>');
document.write('		</button>');
document.write('');
document.write('');
document.write('		<div class = "content coll" id = "instant4">');
document.write('			<div class = "toc2">');
document.write('				<li>4.1 <a href="p9.html" onclick="store(15);setSwitch();"><button class="btn">p9</button></a></li>');
document.write('				<li>4.2 <a href="roots.html" onclick="store(16);setSwitch();"><button class="btn">seeds/roots</button></a></li>');
document.write('				<li>4.3 <a href="forest.html" onclick="store(17);setSwitch();"><button class="btn">forest</button></a></li>');
document.write('				<li>4.4 <a href="ccw2.html" onclick="store(18);setSwitch();"><button class="btn">ccw2</button></a></li>');
document.write('				<li>4.5 <a href="i2.html" onclick="store(19);setSwitch();"><button class="btn">i2</button></a></li>');
document.write('				');
document.write('				');
document.write('			</div>');
document.write('		</div>');
document.write('');
document.write('		<button data-for = "instant5" type="button" class="collapsibleidx" id="here_instant" onclick="carryOn(\'instant5\');">');
document.write('			5 <a href="#" onClick="return false;">Misc</a>');
document.write('		</button>');
document.write('');
document.write('		<div class = "content coll" id = "instant5">');
document.write('			<div class = "toc2">');
document.write('				<li>5.1 <a href="constellation.html" onclick="store(20);setSwitch();"><button class="btn">Constellation</button></a></li>');
document.write('				<li>5.2 <a href="friend.html" onclick="store(21);setSwitch();"><button class="btn">Help Me, Friend</button></a></li>');
document.write('				<li>5.3 <a href="frames.html" onclick="store(22);setSwitch();"><button class="btn">FRAMES</button></a></li>');
document.write('			</div>');
document.write('		</div>');
document.write('');
document.write('		<button data-for = "instant6" type="button" class="collapsibleidx" id="here_instant" onclick="carryOn(\'instant6\');">');
document.write('			6 <a href="#" onClick="return false;">Engineering</a>');
document.write('		</button>');
document.write('');
document.write('		<div class = "content coll" id = "instant6">');
document.write('			<div class = "toc2">');
document.write('				<li>6.1 <a href="l94.html" onclick="store(23);setSwitch();"><button class="btn">L94 Amp</button></a></li>');
document.write('				<li>6.2 <a href="voc.html" onclick="store(24);setSwitch();"><button class="btn">VOC Sensing</button></a></li>');
document.write('			</div>');
document.write('		</div>');
document.write('');
document.write('');
document.write('');
document.write('	<div class = "no_coll">');
document.write('		<button type="button" class="no_coll" id = "about">');
document.write('			7 <a href="about_desktop.html" onclick="store(25);setSwitch();"><button class="btn">About</button></a>');
document.write('		</button>');
document.write('	</div>');
document.write('</ul>');
document.write('');
document.write('');
document.write('');
document.write('</div>');
document.write('');
